CREATE TABLE IF NOT EXISTS `pre_annotation_record`
(
    `id`              bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'Primary key',
    `model_id`        bigint(20) DEFAULT NULL COMMENT 'Optional model id',
    `dataset_id`      bigint(20) NOT NULL COMMENT 'Primary dataset id',
    `dataset_ids`     json NOT NULL COMMENT 'Selected dataset ids',
    `name`            varchar(128) DEFAULT NULL COMMENT 'Pre-annotation task name',
    `source_mode`     enum ('AI','V2V','HYBRID') NOT NULL COMMENT 'Draft source',
    `status`          enum ('STARTED','RUNNING','READY','FAILURE','COMMITTED') NOT NULL DEFAULT 'STARTED',
    `data_count`      bigint(20) NOT NULL DEFAULT 0,
    `data_ids`        json NOT NULL,
    `committed_data_ids` json DEFAULT NULL COMMENT 'Frames already committed as ground truth',
    `config_path`     varchar(512) DEFAULT NULL,
    `checkpoint_path` varchar(512) DEFAULT NULL,
    `source_point_dim` int DEFAULT NULL,
    `model_input_dim` int DEFAULT NULL,
    `iou_threshold`   decimal(5,4) NOT NULL DEFAULT 0.5000,
    `predictions`     json DEFAULT NULL COMMENT 'Editable draft boxes grouped by data id',
    `occ_artifacts`   json DEFAULT NULL COMMENT 'AI OCC artifacts grouped by data id',
    `output_path`     varchar(512) DEFAULT NULL,
    `log_path`        varchar(512) DEFAULT NULL,
    `error_reason`    varchar(1024) DEFAULT NULL,
    `commit_summary`  json DEFAULT NULL,
    `is_deleted`      bit(1) NOT NULL DEFAULT b'0',
    `created_at`      datetime DEFAULT CURRENT_TIMESTAMP,
    `created_by`      bigint(20) DEFAULT NULL,
    `updated_at`      datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    `updated_by`      bigint(20) DEFAULT NULL,
    PRIMARY KEY (`id`),
    KEY `idx_pre_annotation_dataset` (`dataset_id`),
    KEY `idx_pre_annotation_model` (`model_id`),
    KEY `idx_pre_annotation_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Independent pre-annotation jobs';
